api_platform:
  # title: API Platform
  # mapping:
  #     paths: ['%kernel.project_dir%/src/Entity']
  # patch_formats:
  #     json: ['application/merge-patch+json']

  # # Enabling only JSON-LD and JSON formats while disabling HTML format
  # formats:
  #     jsonld:
  #         mime_types: ['application/ld+json']
  #     json:
  #         mime_types: ['application/json']
  
  # # Disabling the displaying of the API documentation 
  # # enable_swagger_ui: false
  # # enable_re_doc: false
  # # enable_docs: false
  # swagger:
  #   versions: [3]
    # api_keys:
    #     JWT:
    #       name: Authorization
    #       type: header